plugins { id 'com.android.application' }

android {
    namespace 'com.hellobaroda.navratri'
    compileSdk 35
    defaultConfig {
        applicationId 'com.hellobaroda.navratri'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '2.0'
    }
}

dependencies {
    implementation 'com.android.billingclient:billing:9.1.0'
}
