package com.hellobaroda.navratri;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import android.text.InputType;
import org.json.*;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity2 extends Activity {
    final int MAROON=Color.rgb(133,0,31), DEEP=Color.rgb(58,0,20), GOLD=Color.rgb(255,201,40), CREAM=Color.rgb(255,247,231), INK=Color.rgb(33,8,18), WHITE=Color.WHITE, MUTED=Color.rgb(111,91,96), SOFT=Color.rgb(250,238,229);
    SupabaseApi api=new SupabaseApi(); ExecutorService io=Executors.newSingleThreadExecutor(); LinearLayout root,body; String mode="queen",name="",bio=""; int day=1; Uri selected; ImageView preview;
    int dp(float x){return (int)(x*getResources().getDisplayMetrics().density+.5f);}
    GradientDrawable shape(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(r));return g;}
    TextView tx(String s,float size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setFontFeatureSettings("kern");t.setPadding(dp(2),dp(3),dp(2),dp(3));if(bold)t.setTypeface(null,1);return t;}
    Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setAllCaps(false);b.setTextColor(WHITE);b.setMinHeight(dp(52));b.setBackground(shape(MAROON,16));b.setPadding(dp(16),dp(8),dp(16),dp(8));b.setElevation(dp(2));return b;}
    Button secondary(String s){Button b=primary(s);b.setTextColor(MAROON);b.setBackground(shape(WHITE,16));b.setElevation(dp(1));return b;}
    EditText input(String hint){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.rgb(145,125,130));e.setTextColor(INK);e.setTextSize(16);e.setSingleLine(true);e.setPadding(dp(16),0,dp(16),0);e.setBackground(shape(WHITE,14));return e;}
    LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;}
    void gap(int h){Space s=new Space(this);body.addView(s,new LinearLayout.LayoutParams(1,dp(h)));}

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);showWelcome();}
    void base(String title,boolean nav){
        root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CREAM);
        root.setOnApplyWindowInsetsListener((v,in)->{v.setPadding(0,in.getSystemWindowInsetTop(),0,in.getSystemWindowInsetBottom());return in;});
        LinearLayout bar=row();bar.setPadding(dp(10),dp(4),dp(10),dp(4));bar.setBackgroundColor(DEEP);
        if(title.length()>0){Button back=new Button(this);back.setText("‹");back.setTextSize(30);back.setTextColor(WHITE);back.setBackgroundColor(Color.TRANSPARENT);back.setContentDescription("Back");back.setOnClickListener(v->home());bar.addView(back,new LinearLayout.LayoutParams(dp(48),dp(56)));}
        ImageView icon=new ImageView(this);icon.setImageResource(com.hellobaroda.navratri.R.drawable.ic_hello_baroda);icon.setPadding(dp(8),dp(8),dp(8),dp(8));bar.addView(icon,new LinearLayout.LayoutParams(dp(52),dp(56)));
        TextView h=tx(title.length()==0?"Hello! Baroda":title,19,WHITE,true);h.setGravity(Gravity.CENTER_VERTICAL);bar.addView(h,new LinearLayout.LayoutParams(0,dp(56),1));
        if(title.equals("Home")){Button bell=new Button(this);bell.setText("♢");bell.setTextSize(22);bell.setTextColor(GOLD);bell.setBackgroundColor(Color.TRANSPARENT);bar.addView(bell,new LinearLayout.LayoutParams(dp(44),dp(56)));}
        root.addView(bar);
        ScrollView sc=new ScrollView(this);sc.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(16),dp(16),dp(nav?94:24));sc.addView(body);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));
        if(nav)bottomNav();setContentView(root);
    }
    void bottomNav(){LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.HORIZONTAL);n.setGravity(Gravity.CENTER);n.setBackgroundColor(WHITE);String[] a={"⌂\nHome","⌖\nGrounds","＋\nCreate","◌\nChat","♙\nProfile"};for(int i=0;i<a.length;i++){Button b=new Button(this);b.setText(a[i]);b.setTextSize(10);b.setTextColor(DEEP);b.setAllCaps(false);b.setBackgroundColor(WHITE);final int x=i;if(x==0)b.setOnClickListener(v->home());if(x==1)b.setOnClickListener(v->grounds());if(x==2)b.setOnClickListener(v->create());if(x==3)b.setOnClickListener(v->community());if(x==4)b.setOnClickListener(v->profile());n.addView(b,new LinearLayout.LayoutParams(0,dp(64),1));}root.addView(n,new LinearLayout.LayoutParams(-1,dp(64)));}
    LinearLayout cardBox(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(16),dp(16),dp(16));c.setBackground(shape(WHITE,22));c.setElevation(dp(3));return c;}
    void logoHeader(String kicker,String sub){LinearLayout r=row();ImageView im=new ImageView(this);im.setImageResource(R.drawable.ic_hello_baroda);r.addView(im,new LinearLayout.LayoutParams(dp(62),dp(62)));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);TextView a=tx("Hello! Baroda",27,MAROON,true);TextView b=tx(kicker,12,DEEP,true);t.addView(a);t.addView(b);r.addView(t,new LinearLayout.LayoutParams(0,-2,1));body.addView(r);if(sub!=null)body.addView(tx(sub,13,MUTED,false));}

    void showWelcome(){base("",false);logoHeader("VADODARA • NAVRATRI COMMUNITY","Garba • People • Places • Culture");gap(18);LinearLayout hero=cardBox();hero.setBackground(shape(DEEP,26));TextView a=tx("Same City.\nDifferent Vibes.\nOne Navratri.",29,WHITE,true);hero.addView(a);hero.addView(tx("A premium home for Vadodara's Garba community.",14,Color.rgb(242,221,225),false));body.addView(hero);gap(18);Button start=primary("Get Started  →");body.addView(start,new LinearLayout.LayoutParams(-1,dp(54)));start.setOnClickListener(v->modeChoice());gap(10);Button login=secondary("I already have an account");body.addView(login,new LinearLayout.LayoutParams(-1,dp(54)));login.setOnClickListener(v->login());gap(18);TextView note=tx("HELLO! BARODA  •  2026 NAVRATRI",11,MAROON,true);note.setGravity(Gravity.CENTER);body.addView(note);}

    void modeChoice(){base("Choose your mode",false);TextView intro=tx("Your vibe. Your community. Your Navratri.",14,MUTED,false);intro.setGravity(Gravity.CENTER);body.addView(intro);gap(14);modeTile("QUEEN MODE","Grace • Garba • Community","👸",PINK,()->{mode="queen";login();});gap(12);modeTile("KING MODE","Energy • Garba • Brotherhood","👑",Color.rgb(176,108,0),()->{mode="king";login();});gap(16);TextView q=tx("Same City • Different Vibes • One Navratri",13,MAROON,true);q.setGravity(Gravity.CENTER);body.addView(q);}
    void modeTile(String title,String sub,String emoji,int color,View.OnClickListener click){LinearLayout c=cardBox();c.setBackground(shape(color,24));c.setGravity(Gravity.CENTER);TextView e=tx(emoji,58,WHITE,true);e.setGravity(Gravity.CENTER);c.addView(e);TextView t=tx(title,21,WHITE,true);t.setGravity(Gravity.CENTER);c.addView(t);TextView s=tx(sub,13,Color.rgb(255,242,245),false);s.setGravity(Gravity.CENTER);c.addView(s);body.addView(c,new LinearLayout.LayoutParams(-1,dp(190)));c.setOnClickListener(click);}

    void login(){base("Sign in",false);logoHeader(mode.equals("king")?"KING MODE 👑":"QUEEN MODE 👸","Vadodara • Navratri Community");gap(14);LinearLayout c=cardBox();TextView title=tx("Welcome back",23,INK,true);c.addView(title);c.addView(tx("Sign in to your online Hello! Baroda community.",13,MUTED,false));EditText email=input("Email address");c.addView(email,new LinearLayout.LayoutParams(-1,dp(54)));sp(c,8);EditText pass=input("Password");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);c.addView(pass,new LinearLayout.LayoutParams(-1,dp(54)));sp(c,14);Button go=primary("Log in");c.addView(go,new LinearLayout.LayoutParams(-1,dp(52)));sp(c,8);Button create=secondary("Create new account");c.addView(create,new LinearLayout.LayoutParams(-1,dp(52)));body.addView(c);create.setOnClickListener(v->signupForm(email,pass));go.setOnClickListener(v->auth(false,email.getText().toString(),pass.getText().toString(),""));}
    void signupForm(EditText oldEmail,EditText oldPass){base("Create account",false);logoHeader("JOIN HELLO! BARODA","People • Places • Culture");gap(14);LinearLayout c=cardBox();EditText name=input("Your name");EditText email=input("Email address");EditText pass=input("Password (6+ characters)");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);c.addView(name,new LinearLayout.LayoutParams(-1,dp(54)));sp(c,8);c.addView(email,new LinearLayout.LayoutParams(-1,dp(54)));sp(c,8);c.addView(pass,new LinearLayout.LayoutParams(-1,dp(54)));sp(c,14);Button b=primary("Create account online");c.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));body.addView(c);b.setOnClickListener(v->auth(true,email.getText().toString(),pass.getText().toString(),name.getText().toString()));}
    void sp(LinearLayout l,int h){Space s=new Space(this);l.addView(s,new LinearLayout.LayoutParams(1,dp(h)));}
    void auth(boolean signup,String e,String p,String n){if(e.trim().isEmpty()||p.length()<6){toast("Enter a valid email and a password of 6+ characters");return;}toast("Connecting securely…");io.execute(()->{boolean ok=signup?api.signUp(e.trim(),p,n.trim().isEmpty()?"Garba Friend":n.trim()):api.login(e.trim(),p);if(ok){JSONObject o=api.loadProfile();name=o.optString("full_name",n);bio=o.optString("bio","");mode=o.optString("mode",mode);day=o.optInt("navratri_day",1);}runOnUiThread(()->{if(ok)home();else toast(api.error);});});}

    void home(){base("Home",true);LinearLayout hero=cardBox();hero.setBackground(shape(DEEP,24));hero.addView(tx("HELLO, "+(name.isEmpty()?"GARBA FRIEND":name.toUpperCase(Locale.ROOT)),12,GOLD,true));hero.addView(tx("Day "+day+"  •  "+(mode.equals("king")?"KING MODE 👑":"QUEEN MODE 👸"),25,WHITE,true));hero.addView(tx("Connect • discover • celebrate Vadodara",13,Color.rgb(242,221,225),false));body.addView(hero);gap(14);TextView st=tx("NAVRATRI DAYS",12,MAROON,true);body.addView(st);HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout dr=row();for(int i=1;i<=12;i++){Button b=primary("Day "+i);b.setTextSize(11);b.setTextColor(i==day?DEEP:WHITE);b.setBackground(shape(i==day?GOLD:PINK,14));final int d=i;b.setOnClickListener(v->{day=d;saveOnline();home();});dr.addView(b,new LinearLayout.LayoutParams(dp(68),dp(44)));Space x=new Space(this);dr.addView(x,new LinearLayout.LayoutParams(dp(6),1));}hs.addView(dr);body.addView(hs,new LinearLayout.LayoutParams(-1,dp(50)));gap(14);TextView ex=tx("EXPLORE",12,MAROON,true);body.addView(ex);LinearLayout acts=row();String[] aa={"📍\nGrounds","🔥\nTrending","📅\nDays","👥\nCommunity"};for(int i=0;i<4;i++){Button b=primary(aa[i]);b.setTextSize(11);b.setBackground(shape(i==2?GOLD:(i==1?PINK:MAROON),18));b.setTextColor(i==2?DEEP:WHITE);final int x=i;if(x==0)b.setOnClickListener(v->grounds());if(x==1)b.setOnClickListener(v->trending());if(x==2)b.setOnClickListener(v->days());if(x==3)b.setOnClickListener(v->community());acts.addView(b,new LinearLayout.LayoutParams(0,dp(68),1));if(i<3){Space s=new Space(this);acts.addView(s,new LinearLayout.LayoutParams(dp(6),1));}}body.addView(acts);gap(18);sectionTitle("Popular Garba Grounds","See all",v->grounds());loadGrounds();gap(18);sectionTitle("Community moments","Trending",v->trending());loadPosts(5);}
    void sectionTitle(String a,String b,View.OnClickListener l){LinearLayout r=row();TextView t=tx(a,19,INK,true);r.addView(t,new LinearLayout.LayoutParams(0,dp(44),1));Button x=secondary(b);x.setTextSize(11);x.setOnClickListener(l);r.addView(x,new LinearLayout.LayoutParams(dp(88),dp(42)));body.addView(r);}
    void loadGrounds(){io.execute(()->{JSONArray a=api.venues();runOnUiThread(()->{if(a.length()==0){body.addView(info("No grounds yet","The directory is online and ready for verified/community-submitted grounds."));return;}LinearLayout r=row();for(int i=0;i<Math.min(3,a.length());i++){JSONObject o=a.optJSONObject(i);LinearLayout c=cardBox();c.setPadding(dp(10),dp(10),dp(10),dp(10));c.addView(tx("📍",24,PINK,true));c.addView(tx(o.optString("name","Garba Ground"),13,INK,true));c.addView(tx(o.optString("area","Vadodara"),11,MUTED,false));r.addView(c,new LinearLayout.LayoutParams(0,dp(125),1));if(i<2){Space s=new Space(this);r.addView(s,new LinearLayout.LayoutParams(dp(7),1));}}body.addView(r);});});}
    TextView info(String a,String b){TextView t=tx(a+"\n"+b,14,INK,false);t.setPadding(dp(16),dp(14),dp(16),dp(14));t.setBackground(shape(WHITE,18));return t;}

    void grounds(){base("Garba Grounds",true);body.addView(tx("Find your Garba place",24,INK,true));body.addView(tx("Vadodara directory • community submitted • verify before visiting",12,MUTED,false));gap(10);EditText s=input("Search grounds, area or venue…");body.addView(s,new LinearLayout.LayoutParams(-1,dp(54)));gap(10);LinearLayout filters=row();for(String x:new String[]{"All","Popular","Nearby","A–Z"}){Button b=secondary(x);b.setTextSize(11);filters.addView(b,new LinearLayout.LayoutParams(0,dp(44),1));}body.addView(filters);gap(10);io.execute(()->{JSONArray a=api.venues();runOnUiThread(()->renderGrounds(a,s));});Button add=primary("＋ Add Ground");body.addView(add,new LinearLayout.LayoutParams(-1,dp(52)));add.setOnClickListener(v->addGround());}
    void renderGrounds(JSONArray a,EditText s){LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);Runnable r=()->{list.removeAllViews();String q=s.getText().toString().toLowerCase(Locale.ROOT).trim();int n=0;for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String nm=o.optString("name","Venue"),ar=o.optString("area","");if(!q.isEmpty()&&!nm.toLowerCase(Locale.ROOT).contains(q)&&!ar.toLowerCase(Locale.ROOT).contains(q))continue;n++;LinearLayout c=cardBox();c.addView(tx("📍  "+nm,17,MAROON,true));c.addView(tx(ar+"\n"+o.optString("address","")+"\n"+(o.optBoolean("verified",false)?"✓ Verified":"Community submitted"),12,INK,false));list.addView(c);sp(list,8);}if(n==0)list.addView(info("No matching ground","Try another search or add a ground."));};r.run();s.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence x,int a,int b,int c){}public void onTextChanged(CharSequence x,int a,int b,int c){r.run();}public void afterTextChanged(android.text.Editable e){}});}
    void addGround(){if(!api.isLoggedIn()){toast("Please sign in first");return;}LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);EditText n=input("Ground / venue name"),a=input("Address"),ar=input("Area"),d=input("Description");b.addView(n);sp(b,7);b.addView(a);sp(b,7);b.addView(ar);sp(b,7);b.addView(d);new AlertDialog.Builder(this).setTitle("Add Garba Ground").setView(b).setNegativeButton("Cancel",null).setPositiveButton("Submit",(x,w)->io.execute(()->{boolean ok=api.addVenue(n.getText().toString().trim(),a.getText().toString().trim(),ar.getText().toString().trim(),d.getText().toString().trim());runOnUiThread(()->{toast(ok?"Ground added online":"Could not add ground: "+api.error);if(ok)grounds();});})).show();}

    void create(){base("Create Post",true);body.addView(tx("Share your Navratri moment",24,INK,true));body.addView(tx("Post to the online Hello! Baroda community.",13,MUTED,false));gap(12);LinearLayout p=cardBox();preview=new ImageView(this);preview.setImageResource(R.drawable.ic_hello_baroda);preview.setScaleType(ImageView.ScaleType.CENTER_INSIDE);p.addView(preview,new LinearLayout.LayoutParams(-1,dp(190)));Button pick=secondary("＋ Add Photo");p.addView(pick,new LinearLayout.LayoutParams(-1,dp(50)));body.addView(p);pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,7);});gap(10);EditText cap=input("Write a caption…");cap.setSingleLine(false);cap.setMinLines(3);cap.setGravity(Gravity.TOP);body.addView(cap,new LinearLayout.LayoutParams(-1,dp(105)));gap(10);TextView tag=tx(mode.equals("king")?"👑 KING MODE":"👸 QUEEN MODE",13,MAROON,true);tag.setPadding(dp(14),dp(12),dp(14),dp(12));tag.setBackground(shape(WHITE,16));body.addView(tag);gap(10);Button post=primary("Publish online  ✦");body.addView(post);post.setOnClickListener(v->publish(cap.getText().toString().trim()));}
    void publish(String cap){if(cap.isEmpty()){toast("Write a caption first");return;}if(!api.isLoggedIn()){toast("Please sign in first");return;}toast("Publishing online…");io.execute(()->{String path="";boolean ok=true;try{if(selected!=null){InputStream in=getContentResolver().openInputStream(selected);ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);in.close();path=api.userId()+"/"+System.currentTimeMillis()+".jpg";ok=api.uploadImage(out.toByteArray(),"post_media",path);}}catch(Exception e){ok=false;api.error=e.getMessage();}if(ok)ok=api.addPost(cap,day,path);boolean done=ok;runOnUiThread(()->{toast(done?"Posted online 🎉":"Publish failed: "+api.error);if(done)home();});});}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==7&&c==RESULT_OK&&d!=null){selected=d.getData();if(preview!=null)preview.setImageURI(selected);}}

    void trending(){base("Trending",true);body.addView(tx("🔥 Trending Garba",24,INK,true));body.addView(tx("Fresh moments from the community",13,MUTED,false));gap(10);loadPosts(30);}
    void loadPosts(int limit){io.execute(()->{JSONArray a=api.posts();runOnUiThread(()->{for(int i=0;i<a.length()&&i<limit;i++){JSONObject o=a.optJSONObject(i);if(o!=null)postCard(o);}if(a.length()==0)body.addView(info("No posts yet","Be the first to share a Garba moment."));});});}
    void postCard(JSONObject o){LinearLayout c=cardBox();c.addView(tx((mode.equals("king")?"👑":"👸")+"  Community  •  Day "+o.optInt("navratri_day",0),12,MAROON,true));String media=o.optString("media_path","");if(!media.isEmpty()){ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);c.addView(im,new LinearLayout.LayoutParams(-1,dp(190)));loadImage(api.publicUrl("post_media",media),im);}c.addView(tx(o.optString("caption","Garba moment"),16,INK,true));LinearLayout a=row();Button like=secondary("♡ Like"),com=secondary("💬 Comment");a.addView(like,new LinearLayout.LayoutParams(0,dp(46),1));a.addView(com,new LinearLayout.LayoutParams(0,dp(46),1));c.addView(a);body.addView(c);gap(10);String id=o.optString("id","");like.setOnClickListener(v->io.execute(()->api.like(id)));com.setOnClickListener(v->comments(id));}
    void loadImage(String url,ImageView target){io.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);Bitmap b=BitmapFactory.decodeStream(c.getInputStream());runOnUiThread(()->{if(b!=null)target.setImageBitmap(b);});}catch(Exception ignored){}});}
    void comments(String id){io.execute(()->{JSONArray a=api.comments(id);runOnUiThread(()->{LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null)b.addView(tx("• "+o.optString("body"),14,INK,false));}EditText e=input("Add a comment…");b.addView(e);new AlertDialog.Builder(this).setTitle("Comments").setView(b).setNegativeButton("Close",null).setPositiveButton("Post",(x,w)->io.execute(()->api.addComment(id,e.getText().toString().trim()))).show();});});}

    void days(){base("Navratri Days",true);body.addView(tx("12 days. One city. One celebration.",23,INK,true));body.addView(tx("Select a day to personalize your experience.",13,MUTED,false));gap(12);String[] n={"Pratipada","Dwitiya","Tritiya","Chaturthi","Panchami","Shashthi","Saptami","Ashtami","Navami","Dashami","Ekadashi","Dwadashi"};for(int i=1;i<=12;i++){Button b=primary("Day "+i+"   •   "+n[i-1]);b.setBackground(shape(i==day?GOLD:PINK,16));b.setTextColor(i==day?DEEP:WHITE);final int x=i;b.setOnClickListener(v->{day=x;saveOnline();home();});body.addView(b,new LinearLayout.LayoutParams(-1,dp(52)));gap(7);}}

    void community(){base("Community",true);body.addView(tx("👥 Vadodara Garba Community",23,INK,true));body.addView(tx("Plans • moments • helpful local conversations",13,MUTED,false));gap(10);io.execute(()->{String cid=api.communityId();if(cid.isEmpty()){runOnUiThread(()->body.addView(info("Community is not configured yet","The Supabase community needs to be created before online chat can start.")));return;}api.joinCommunity(cid);JSONArray a=api.messages(cid);runOnUiThread(()->{for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null){body.addView(info("Community message",o.optString("body")));gap(6);}}EditText e=input("Message…");body.addView(e,new LinearLayout.LayoutParams(-1,dp(54)));gap(8);Button send=primary("Send message");body.addView(send);send.setOnClickListener(v->{String m=e.getText().toString().trim();if(m.isEmpty())return;io.execute(()->{boolean ok=api.sendMessage(cid,m);runOnUiThread(()->{toast(ok?"Message sent":"Send failed: "+api.error);if(ok)community();});});});});});}

    void profile(){base("My Profile",true);LinearLayout p=cardBox();p.setBackground(shape(DEEP,24));TextView a=tx(mode.equals("king")?"👑":"👸",48,GOLD,true);a.setGravity(Gravity.CENTER);p.addView(a);TextView n=tx(name.isEmpty()?"Garba Friend":name,22,WHITE,true);n.setGravity(Gravity.CENTER);p.addView(n);TextView s=tx("Garba • Culture • Vadodara",12,Color.rgb(242,221,225),false);s.setGravity(Gravity.CENTER);p.addView(s);body.addView(p);gap(12);LinearLayout m=row();Button k=primary("👑 King Mode"),q=secondary("♕ Queen Mode");m.addView(k,new LinearLayout.LayoutParams(0,dp(48),1));m.addView(q,new LinearLayout.LayoutParams(0,dp(48),1));body.addView(m);k.setOnClickListener(v->{mode="king";saveOnline();profile();});q.setOnClickListener(v->{mode="queen";saveOnline();profile();});gap(10);EditText ne=input("Your name");ne.setText(name);body.addView(ne,new LinearLayout.LayoutParams(-1,dp(54)));gap(8);EditText bi=input("Bio");bi.setText(bio);bi.setSingleLine(false);bi.setMinLines(2);body.addView(bi,new LinearLayout.LayoutParams(-1,dp(82)));gap(10);Button save=primary("Save profile online");body.addView(save);save.setOnClickListener(v->{name=ne.getText().toString().trim();bio=bi.getText().toString().trim();saveOnline();toast("Profile saved online");});gap(10);Button out=secondary("Log out");body.addView(out);out.setOnClickListener(v->{api.logout();name="";bio="";showWelcome();});}
    void saveOnline(){if(api.isLoggedIn())io.execute(()->api.saveProfile(name,mode,day,bio));}
    void toast(String s){Toast.makeText(this,s==null?"Something went wrong":s,Toast.LENGTH_SHORT).show();}
    @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}
