package com.hellobaroda.navratri;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.provider.OpenableColumns;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;import java.util.concurrent.*;

public class MainActivity extends Activity{
  SupabaseApi api=new SupabaseApi(); ExecutorService io=Executors.newSingleThreadExecutor(); LinearLayout root,content; int MAROON=Color.rgb(102,0,32),DEEP=Color.rgb(55,0,20),GOLD=Color.rgb(255,198,38),CREAM=Color.rgb(255,248,232),PINK=Color.rgb(145,0,45); int day=1; String mode="queen"; Uri selected;
  TextView title;
  @Override public void onCreate(Bundle b){super.onCreate(b);showLogin();}
  TextView tv(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(18,14,18,14);if(bold)t.setTypeface(null,1);return t;}
  Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setBackgroundColor(PINK);return b;}
  void base(String heading){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CREAM); LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(DEEP);title=tv(heading,21,Color.WHITE,true);bar.addView(title,new LinearLayout.LayoutParams(0,64,1));root.addView(bar);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(10,12,10,100);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
  void nav(){LinearLayout n=new LinearLayout(this);n.setGravity(Gravity.CENTER);n.setBackgroundColor(DEEP);String[] a={"Home","Grounds","Create","Community","Profile"};for(String s:a){Button b=new Button(this);b.setText(s);b.setTextSize(10);b.setTextColor(GOLD);b.setBackgroundColor(DEEP);n.addView(b,new LinearLayout.LayoutParams(0,58,1));if(s.equals("Home"))b.setOnClickListener(v->home());if(s.equals("Grounds"))b.setOnClickListener(v->grounds());if(s.equals("Create"))b.setOnClickListener(v->create());if(s.equals("Community"))b.setOnClickListener(v->community());if(s.equals("Profile"))b.setOnClickListener(v->profile());}root.addView(n);}
  void showLogin(){base("Hello! Baroda");content.setGravity(Gravity.CENTER_HORIZONTAL);content.addView(tv("👑  Hello! Baroda  👸",28,PINK,true));content.addView(tv("Vadodara • Navratri Community",16,DEEP,true));content.addView(tv("Real online community — not a local-only app",13,Color.DKGRAY,false));EditText email=new EditText(this);email.setHint("Email");content.addView(email);EditText pass=new EditText(this);pass.setHint("Password");pass.setInputType(129);content.addView(pass);EditText name=new EditText(this);name.setHint("Name (for new account)");content.addView(name);Button login=btn("LOGIN");content.addView(login);Button signup=btn("CREATE ACCOUNT");content.addView(signup);login.setOnClickListener(v->auth(false,email.getText().toString(),pass.getText().toString(),name.getText().toString()));signup.setOnClickListener(v->auth(true,email.getText().toString(),pass.getText().toString(),name.getText().toString()));}
  void auth(boolean signup,String e,String p,String n){if(e.trim().isEmpty()||p.length()<6){toast("Enter a valid email and password (6+ characters)");return;}busy(true);io.execute(()->{boolean ok=signup?api.signUp(e.trim(),p,n.trim().isEmpty()?"Garba Friend":n.trim()):api.login(e.trim(),p);runOnUiThread(()->{busy(false);if(ok){day=1;mode="queen";home();}else toast(api.error);});});}
  void busy(boolean x){if(x)Toast.makeText(this,"Connecting online…",Toast.LENGTH_SHORT).show();}
  void home(){base("Hello! Baroda");TextView hero=tv("Vadodara • Navratri\n"+(mode.equals("king")?"KING MODE 👑":"QUEEN MODE 👸")+"\nDay "+day,25,Color.WHITE,true);hero.setGravity(Gravity.CENTER);hero.setBackgroundColor(MAROON);content.addView(hero,new LinearLayout.LayoutParams(-1,180));Button modeB=btn(mode.equals("king")?"Switch to QUEEN MODE":"Switch to KING MODE");content.addView(modeB);modeB.setOnClickListener(v->{mode=mode.equals("king")?"queen":"king";saveProfile();home();});content.addView(tv("Explore",20,DEEP,true));Button tr=btn("🔥 Trending");content.addView(tr);tr.setOnClickListener(v->trending());Button d=btn("★ Navratri Days 1–12");content.addView(d);d.setOnClickListener(v->days());Button g=btn("⌖ Garba Grounds");content.addView(g);g.setOnClickListener(v->grounds());content.addView(tv("Your online community",18,DEEP,true));loadPosts(false);nav();}
  void loadPosts(boolean onlyTrending){io.execute(()->{JSONArray a=api.posts();runOnUiThread(()->{for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String cap=o.optString("caption","Garba moment");int pd=o.optInt("navratri_day",0);if(onlyTrending&&i>9)break;content.addView(tv("✦  "+cap+"\nDay "+(pd>0?pd:"—")+"  •  Online community",15,DEEP,false));}});});}
  void grounds(){base("Garba Grounds");content.addView(tv("📍 Vadodara Garba Grounds",22,DEEP,true));content.addView(tv("Community-submitted directory. Unverified entries are clearly marked.",12,Color.DKGRAY,false));EditText search=new EditText(this);search.setHint("Search venue / area");content.addView(search);Button add=btn("＋ Add Ground");content.addView(add);add.setOnClickListener(v->addGround());io.execute(()->{JSONArray a=api.venues();runOnUiThread(()->{if(a.length()==0)content.addView(tv("No venues have been added yet. Be the first to add one.",14,DEEP,false));for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(12,12,12,12);TextView x=tv(o.optString("name","Venue"),17,PINK,true);card.addView(x);card.addView(tv(o.optString("area","")+"\n"+o.optString("address","")+"\n"+(o.optBoolean("verified",false)?"✓ Verified":"Community submitted"),12,DEEP,false));content.addView(card);}});});nav();}
  void addGround(){if(!api.isLoggedIn()){toast("Please login first");return;}LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText n=new EditText(this);n.setHint("Ground / venue name");EditText a=new EditText(this);a.setHint("Address");EditText ar=new EditText(this);ar.setHint("Area in Vadodara");EditText de=new EditText(this);de.setHint("Description");box.addView(n);box.addView(a);box.addView(ar);box.addView(de);new AlertDialog.Builder(this).setTitle("Add Garba Ground").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Submit",(q,w)->io.execute(()->{boolean ok=api.addVenue(n.getText().toString(),a.getText().toString(),ar.getText().toString(),de.getText().toString());runOnUiThread(()->{toast(ok?"Ground added online":"Could not add ground: "+api.error);if(ok)grounds();});})).show();}
  void create(){base("Create");content.addView(tv("Share your Navratri moment",23,DEEP,true));content.addView(tv("Your post will be stored online for the community.",13,Color.DKGRAY,false));Button pick=btn("＋ Select Photo");content.addView(pick);pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,7);});EditText cap=new EditText(this);cap.setHint("Write a caption…");cap.setMinLines(3);content.addView(cap);Button post=btn("PUBLISH ONLINE");content.addView(post);post.setOnClickListener(v->{String c=cap.getText().toString().trim();if(c.isEmpty()){toast("Write a caption");return;}io.execute(()->{boolean ok=api.addPost(c,day);runOnUiThread(()->{toast(ok?"Published online":"Publish failed: "+api.error);if(ok)home();});});});nav();}
  @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==7&&c==RESULT_OK&&d!=null){selected=d.getData();toast("Photo selected");}}
  void trending(){base("🔥 Trending");content.addView(tv("Trending Garba content in the community",20,DEEP,true));loadPosts(true);nav();}
  void days(){base("Navratri Days");content.addView(tv("Celebrate all 12 days",22,DEEP,true));for(int i=1;i<=12;i++){Button b=btn("Day "+i);content.addView(b);final int x=i;b.setOnClickListener(v->{day=x;saveProfile();home();});}nav();}
  void community(){base("Community");content.addView(tv("💬 Vadodara Garba Community",20,DEEP,true));io.execute(()->{String cid=api.communityId();if(cid.isEmpty()){runOnUiThread(()->toast("Community is unavailable"));return;}api.joinCommunity(cid);JSONArray a=api.messages(cid);runOnUiThread(()->{for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null)content.addView(tv("• "+o.optString("body"),14,DEEP,false));}EditText m=new EditText(this);m.setHint("Message…");content.addView(m);Button send=btn("SEND");content.addView(send);send.setOnClickListener(v->io.execute(()->{boolean ok=api.sendMessage(cid,m.getText().toString());runOnUiThread(()->{toast(ok?"Message sent online":"Send failed: "+api.error);if(ok)community();});}));});});nav();}
  void profile(){base("My Profile");content.addView(tv(mode.equals("king")?"👑 KING MODE":"👸 QUEEN MODE",25,PINK,true));EditText n=new EditText(this);n.setHint("Your name");content.addView(n);EditText bio=new EditText(this);bio.setHint("Bio");content.addView(bio);Button save=btn("SAVE PROFILE ONLINE");content.addView(save);save.setOnClickListener(v->{if(n.getText().length()>0)saveName=n.getText().toString();saveProfile();toast("Profile saved online");});Button out=btn("LOG OUT");content.addView(out);out.setOnClickListener(v->{api.logout();showLogin();});nav();}
  String saveName="";void saveProfile(){if(!api.isLoggedIn())return;io.execute(()->api.saveProfile(saveName,mode,day,""));}
  void toast(String s){Toast.makeText(this,s==null?"Unknown error":s,Toast.LENGTH_LONG).show();}
  @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
}