package com.hellobaroda.navratri;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
  AppView v; android.content.SharedPreferences sp;
  final int MAROON=Color.rgb(102,0,32),DEEP=Color.rgb(55,0,20),GOLD=Color.rgb(255,198,38),CREAM=Color.rgb(255,248,232),WHITE=Color.WHITE,MUTED=Color.rgb(112,91,98),PINK=Color.rgb(145,0,45);
  @Override public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("hb",0);v=new AppView(this);setContentView(v);}
  void save(){sp.edit().putBoolean("king",v.king).putInt("day",v.day).putString("name",v.name).apply();}
  void textDialog(String title,String hint,boolean multiline, final String type){
    final EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(!multiline);if(multiline)e.setMinLines(4);
    new AlertDialog.Builder(this).setTitle(title).setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{
      String s=e.getText().toString().trim();if(s.length()==0)return;
      if(type.equals("ground")){v.grounds.add(s);persistList("grounds",v.grounds);Toast.makeText(this,"Ground added to your local directory",Toast.LENGTH_SHORT).show();}
      else if(type.equals("post")){v.posts.add(s);persistList("posts",v.posts);Toast.makeText(this,"Post created",Toast.LENGTH_SHORT).show();}
      else if(type.equals("chat")){v.messages.add(s);persistList("messages",v.messages);Toast.makeText(this,"Message sent",Toast.LENGTH_SHORT).show();}
      else if(type.equals("name")){v.name=s;save();}
      v.invalidate();}).show();
  }
  void login(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(30,5,30,0);EditText n=new EditText(this);n.setHint("Your name");EditText p=new EditText(this);p.setHint("Email or phone");box.addView(n);box.addView(p);new AlertDialog.Builder(this).setTitle("Login / Create account").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Continue",(d,w)->{String s=n.getText().toString().trim();v.name=s.length()>0?s:"Guest";save();v.invalidate();Toast.makeText(this,"Profile saved on this phone",Toast.LENGTH_SHORT).show();}).show();}
  void persistList(String key,ArrayList<String> a){StringBuilder b=new StringBuilder();for(String s:a)b.append(s.replace("|"," ")).append("|");sp.edit().putString(key,b.toString()).apply();}
  ArrayList<String> loadList(String key){ArrayList<String>a=new ArrayList<>();String z=sp.getString(key,"");for(String s:z.split("\\|"))if(s.trim().length()>0)a.add(s);return a;}
  void choosePhoto(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,22);}
  @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==22&&c==RESULT_OK&&d!=null){Uri u=d.getData();if(u!=null){getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);v.photo=u.toString();sp.edit().putString("photo",v.photo).apply();v.invalidate();Toast.makeText(this,"Photo selected for your next post",Toast.LENGTH_SHORT).show();}}}

  class AppView extends View{
    Paint p=new Paint(3); int screen=0,day=sp.getInt("day",3); boolean king=sp.getBoolean("king",false);String name=sp.getString("name","Guest"),photo=sp.getString("photo","");
    ArrayList<String> grounds=loadList("grounds"),posts=loadList("posts"),messages=loadList("messages");
    String[] tabs={"⌂","⌖","＋","◯","♙"};String[] names={"Home","Grounds","Create","Chat","Profile"};
    float sx,sy;int detail=-1;
    AppView(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}
    void rr(Canvas c,float l,float t,float r,float b,int col,float rad){p.setColor(col);p.setStyle(Paint.Style.FILL);c.drawRoundRect(l,t,r,b,rad,rad,p);}
    void stroke(Canvas c,float l,float t,float r,float b,int col,float rad){p.setColor(col);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);c.drawRoundRect(l,t,r,b,rad,rad,p);p.setStyle(Paint.Style.FILL);}
    void tx(Canvas c,String s,float x,float y,float z,int col,boolean bold){p.setColor(col);p.setTextSize(z);p.setTypeface(Typeface.create("sans",bold?Typeface.BOLD:Typeface.NORMAL));c.drawText(s,x,y,p);}
    void ct(Canvas c,String s,float x,float y,float z,int col,boolean bold){p.setTextSize(z);p.setTypeface(Typeface.create("sans",bold?1:0));p.setColor(col);c.drawText(s,x-p.measureText(s)/2,y,p);}
    void bg(Canvas c,float w,float h){p.setShader(new LinearGradient(0,0,0,390,DEEP,PINK,Shader.TileMode.CLAMP));c.drawRect(0,0,w,390,p);p.setShader(null);}
    @Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();c.drawColor(CREAM);if(screen==0)home(c,w,h);else if(screen==1)grounds(c,w,h);else if(screen==2)create(c,w,h);else if(screen==3)chat(c,w,h);else if(screen==4)profile(c,w,h);else if(screen==5)trending(c,w,h);else if(screen==6)days(c,w,h);else if(screen==7)mode(c,w,h);else detail(c,w,h);if(screen!=7)bottom(c,w,h);}
    void top(Canvas c,String title){tx(c,"‹",18,48,38,WHITE,false);tx(c,title,58,43,21,WHITE,true);tx(c,"⋮",getWidth()-35,44,25,WHITE,true);}
    void home(Canvas c,float w,float h){bg(c,w,h);tx(c,"Hello Baroda",18,35,20,WHITE,true);tx(c,"Vadodara  •  Navratri",18,57,10,0xFFFFE5B4,false);ct(c,king?"KING MODE":"QUEEN MODE",w/2,95,14,WHITE,true);ct(c,king?"Energy • Garba • Brotherhood":"Grace • Garba • Community",w/2,115,10,0xFFFFD777,false);
      rr(c,14,135,w-14,318,0xFFFFE9C7,22);ct(c,"NAVRATRI",w/2,160,11,PINK,true);ct(c,"Day "+day,w/2,205,34,PINK,true);ct(c,"Garba  •  People  •  Places  •  Culture",w/2,227,10,MUTED,false);rr(c,27,245,w-27,285,PINK,20);ct(c,"Explore today's Garba  →",w/2,270,12,WHITE,true);
      rr(c,14,330,w-14,462,DEEP,18);ct(c,"✦  GARBA NIGHT  ✦",w/2,370,13,GOLD,true);ct(c,king?"Energy • Dance • Brotherhood":"Grace • Dance • Celebration",w/2,395,16,WHITE,true);ct(c,"Vadodara",w/2,420,11,0xFFFFE8BD,false);
      quick(c,14,478,(w-42)/4,548,"⌖","Grounds");quick(c,24+(w-42)/4,478,2*(w-42)/4+24,548,"♨","Trending");quick(c,34+2*(w-42)/4,478,3*(w-42)/4+34,548,"★","Days");quick(c,44+3*(w-42)/4,478,w-14,548,"♣","Community");
      tx(c,"Popular Garba Grounds",16,580,16,DEEP,true);tx(c,"See All  ›",w-72,580,11,PINK,true);int y=595;String[] base={"United Way Garba","Laxmi Vilas Ground","Alembic Ground"};for(int i=0;i<3;i++)smallGround(c,16+i*((w-46)/3+8),y,16+(i+1)*((w-46)/3)+i*8,y+85,base[i]);
      tx(c,"Your mode",16,710,13,DEEP,true);rr(c,16,720,w/2-8,760,king?GOLD:WHITE,18);ct(c,"KING MODE",(16+w/2-8)/2,746,10,DEEP,true);rr(c,w/2+8,720,w-16,760,!king?GOLD:WHITE,18);ct(c,"QUEEN MODE",(w/2+8+w-16)/2,746,10,DEEP,true);
    }
    void quick(Canvas c,float l,float t,float r,float b,String i,String s){rr(c,l,t,r,b,WHITE,18);ct(c,i,(l+r)/2,t+29,20,PINK,true);ct(c,s,(l+r)/2,t+53,9,DEEP,true);}
    void smallGround(Canvas c,float l,float t,float r,float b,String s){rr(c,l,t,r,b,WHITE,14);rr(c,l+4,t+4,r-4,t+40,MAROON,10);ct(c,"✦",(l+r)/2,t+29,18,GOLD,true);ct(c,s,(l+r)/2,t+58,8,DEEP,true);ct(c,"View details",(l+r)/2,t+73,7,MUTED,false);}
    void grounds(Canvas c,float w,float h){bg(c,w,h);top(c,"Garba Grounds");rr(c,16,65,w-16,108,WHITE,22);tx(c,"⌕  Search grounds in Vadodara...",30,92,12,MUTED,false);String[] f={"All","Popular","Nearby","A to Z"};float x=18;for(String s:f){rr(c,x,122,x+62,154,s.equals("All")?GOLD:WHITE,17);ct(c,s,x+31,143,9,DEEP,true);x+=69;}tx(c,"Vadodara Garba directory",18,184,17,DEEP,true);tx(c,"Add venue information from your community.",18,204,10,MUTED,false);ArrayList<String> list=new ArrayList<>();list.addAll(grounds);if(list.size()==0){empty(c,235,"No custom grounds yet","Tap Add Ground to build your personal directory.");}else{int y=225;for(int i=0;i<list.size();i++){groundRow(c,16,y,w-16,list.get(i),i);y+=92;if(y>h-175)break;}}rr(c,18,h-145,w-18,h-92,PINK,22);ct(c,"＋  Add Ground",w/2,h-111,13,WHITE,true);}
    void groundRow(Canvas c,float l,float t,float r,String s,int i){rr(c,l,t,r,t+82,WHITE,16);rr(c,l+9,t+9,112,t+73,MAROON,12);ct(c,"✦",60,t+48,24,GOLD,true);tx(c,s,124,t+30,13,DEEP,true);tx(c,"Vadodara  •  Community entry",124,t+50,9,MUTED,false);tx(c,"♡",r-38,t+35,20,PINK,false);}
    void empty(Canvas c,float y,String a,String b){rr(c,20,y,getWidth()-20,y+150,WHITE,20);ct(c,"◎",getWidth()/2,y+52,34,GOLD,true);ct(c,a,getWidth()/2,y+85,14,DEEP,true);ct(c,b,getWidth()/2,y+109,10,MUTED,false);}
    void create(Canvas c,float w,float h){bg(c,w,h);top(c,"Create");tx(c,"Share your Navratri moment",18,95,20,DEEP,true);tx(c,"Post photos, videos or a Garba memory.",18,117,11,MUTED,false);rr(c,16,140,w-16,285,WHITE,20);ct(c,photo.length()>0?"✓":"＋",w/2,205,42,PINK,true);ct(c,photo.length()>0?"Photo selected":"Add photo / video",w/2,232,13,PINK,true);rr(c,16,300,w-16,350,PINK,20);ct(c,"Create Post",w/2,331,13,WHITE,true);tx(c,"Recent posts",18,395,16,DEEP,true);int y=420;for(String s:posts){rr(c,18,y,w-18,y+65,WHITE,15);tx(c,"●",32,y+38,18,PINK,true);tx(c,s,60,y+28,12,DEEP,true);tx(c,"Just now  •  Garba community",60,y+47,9,MUTED,false);y+=76;if(y>h-90)break;}}
    void chat(Canvas c,float w,float h){bg(c,w,h);top(c,"Community");String[] defaults={"Vadodara Garba Lovers","United Way Group","King Mode Crew","Queen Mode Circle","Photography Hub"};int y=75;for(String s:defaults){rr(c,16,y,w-16,y+62,WHITE,15);rr(c,26,y+10,70,y+54,MAROON,22);ct(c,"✦",48,y+39,16,GOLD,true);tx(c,s,82,y+27,13,DEEP,true);tx(c,"Community conversation",82,y+45,9,MUTED,false);y+=72;}for(String s:messages){rr(c,16,y,w-16,y+55,0xFFFFE7A8,15);tx(c,"You",30,y+22,10,PINK,true);tx(c,s,30,y+42,11,DEEP,false);y+=64;if(y>h-160)break;}rr(c,16,h-140,w-16,h-88,PINK,20);ct(c,"＋  New conversation",w/2,h-107,13,WHITE,true);}
    void profile(Canvas c,float w,float h){bg(c,w,h);top(c,"My Profile");ct(c,king?"♛":"♕",w/2,105,54,GOLD,true);ct(c,name,w/2,142,20,DEEP,true);ct(c,"Garba  |  Culture  |  Vadodara",w/2,162,10,MUTED,false);rr(c,16,184,w-16,234,WHITE,18);ct(c,name.equals("Guest")?"Login / Create account":"Edit profile",w/2,215,12,PINK,true);String[] rows={"♡  My Bookmarks","▣  My Posts","★  My Events","♧  Invite Friends","⚙  Settings","?  Help & Support"};int y=270;for(String s:rows){tx(c,s,28,y,13,DEEP,true);tx(c,"›",w-35,y,18,MUTED,false);y+=48;}rr(c,16,570,w-16,620,GOLD,20);ct(c,king?"Switch to Queen Mode":"Switch to King Mode",w/2,602,12,DEEP,true);}
    void trending(Canvas c,float w,float h){bg(c,w,h);top(c,"Trending");rr(c,16,65,w-16,108,WHITE,20);ct(c,"🔥  Trending in Vadodara",w/2,92,13,PINK,true);String[] tags={"All","Photos","Videos","Reels"};float x=18;for(String s:tags){rr(c,x,122,x+62,154,s.equals("Photos")?GOLD:WHITE,17);ct(c,s,x+31,143,9,DEEP,true);x+=69;}String[] p={"Garba vibes","Vadodara tonight","King Mode","Queen Mode","Navratri memories"};int y=180;for(String s:p){rr(c,16,y,w-16,y+120,WHITE,18);rr(c,26,y+10,w/2,y+110,DEEP,14);ct(c,"✦",w/4,y+67,30,GOLD,true);tx(c,"#"+s.replace(" ",""),w/2+10,y+42,13,DEEP,true);tx(c,"Community post  •  ♥",w/2+10,y+66,10,MUTED,false);rr(c,w/2+10,y+80,w-28,y+103,0xFFFFE7A8,12);ct(c,"Like  •  Comment  •  Share",3*w/4+2,y+96,8,PINK,true);y+=135;}}
    void days(Canvas c,float w,float h){bg(c,w,h);top(c,"Navratri Days");tx(c,"Explore all 12 days",18,82,20,WHITE,true);tx(c,"Choose a day to view its Garba focus.",18,104,10,0xFFFFE5B4,false);int y=130;for(int i=1;i<=12;i++){float l=18+((i-1)%3)*(w-36)/3,t=y+((i-1)/3)*68,r=l+(w-48)/3;rr(c,l,t,r,t+52,i==day?GOLD:WHITE,15);ct(c,"Day "+i,(l+r)/2,t+22,11,DEEP,true);ct(c,"Navratri",(l+r)/2,t+39,8,MUTED,false);}y=425;rr(c,18,y,w-18,y+205,0xFFFFE9C7,20);ct(c,"NAVRATRI DAY "+day,w/2,y+42,12,PINK,true);ct(c,"Garba • Energy • Community",w/2,y+82,19,DEEP,true);ct(c,"Discover posts, places and people",w/2,y+111,11,MUTED,false);rr(c,40,y+135,w-40,y+180,PINK,20);ct(c,"Explore Day "+day,w/2,y+164,12,WHITE,true);}
    void mode(Canvas c,float w,float h){bg(c,w,h);ct(c,"Choose Your Mode",w/2,70,23,WHITE,true);ct(c,"Play your Navratri your way.",w/2,95,11,0xFFFFD777,false);modeCard(c,18,125,w-18,335,false,"QUEEN MODE","Grace • Garba • Community");modeCard(c,18,355,w-18,565,true,"KING MODE","Energy • Garba • Brotherhood");ct(c,"Same City  •  Different Vibes",w/2,615,13,GOLD,true);ct(c,"One Navratri  •  Hello Baroda",w/2,640,12,WHITE,false);}
    void modeCard(Canvas c,float l,float t,float r,float b,boolean k,String title,String sub){rr(c,l,t,r,b,k?0xFFFFC928:0xFFB40045,28);ct(c,k?"♛":"♕",(l+r)/2,t+105,76,k?DEEP:GOLD,true);ct(c,title,(l+r)/2,t+175,19,k?DEEP:WHITE,true);ct(c,sub,(l+r)/2,t+198,11,k?DEEP:0xFFFFE4EE,false);stroke(c,l,t,r,b,WHITE,28);}
    void detail(Canvas c,float w,float h){bg(c,w,h);top(c,detail>=0&&detail<grounds.size()?grounds.get(detail):"Ground Details");rr(c,16,65,w-16,260,DEEP,20);ct(c,"✦",w/2,145,58,GOLD,true);ct(c,detail>=0&&detail<grounds.size()?grounds.get(detail):"Garba Ground",w/2,198,20,WHITE,true);ct(c,"Vadodara  •  Community directory",w/2,220,10,0xFFFFE5B4,false);rr(c,18,285,w-18,335,WHITE,18);ct(c,"About",w/2,317,12,PINK,true);tx(c,"Information for this venue can be added and verified by the community.",25,375,11,MUTED,false);rr(c,18,420,w-18,470,PINK,20);ct(c,"Add information",w/2,451,13,WHITE,true);}
    void bottom(Canvas c,float w,float h){float top=h-68;rr(c,0,top,w,h,WHITE,0);for(int i=0;i<5;i++){float x=w*(i+.5f)/5;int col=screen==i?PINK:MUTED;ct(c,tabs[i],x,top+27,17,col,true);ct(c,names[i],x,top+48,7,col,screen==i);}}
    @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()==0){sx=e.getX();sy=e.getY();return true;}if(e.getAction()!=1)return true;float x=e.getX(),y=e.getY(),w=getWidth(),h=getHeight();
      if(screen==7){if(y>110&&y<345){king=false;save();screen=0;}else if(y>345&&y<585){king=true;save();screen=0;}invalidate();return true;}
      if(y>h-82){screen=Math.min(4,(int)(x/(w/5)));detail=-1;invalidate();return true;}
      if(screen==0){if(y>135&&y<290){day++;if(day>12)day=1;save();invalidate();return true;}if(y>470&&y<555){if(x<w/4)screen=1;else if(x<w/2)screen=5;else if(x<3*w/4)screen=6;else screen=3;invalidate();return true;}if(y>705){king=x<w/2;save();invalidate();return true;}if(y>575&&y<700){screen=1;invalidate();return true;}}
      else if(screen==1){if(y>h-170){textDialog("Add Ground","Ground name",false,"ground");return true;}if(y>215&&y<h-170&&grounds.size()>0){int i=(int)((y-225)/92);if(i>=0&&i<grounds.size()){detail=i;screen=8;invalidate();return true;}}}
      else if(screen==2){if(y>135&&y<285){choosePhoto();return true;}if(y>295&&y<360){textDialog("Create Post","Write your Garba moment",true,"post");return true;}}
      else if(screen==3){if(y>h-160){textDialog("New conversation","Write a message",false,"chat");return true;}}
      else if(screen==4){if(y>175&&y<245){if(name.equals("Guest"))login();else textDialog("Edit profile","Your name",false,"name");return true;}if(y>555&&y<640){king=!king;save();invalidate();return true;}}
      else if(screen==5){if(y>120&&y<170){invalidate();return true;}}
      else if(screen==6){if(y>=125&&y<410){int col=(int)((x-18)/((w-36)/3));int row=(int)((y-130)/68);if(col>=0&&col<3&&row>=0&&row<4){day=row*3+col+1;if(day>12)day=12;save();invalidate();return true;}}}
      else if(screen==8){if(y>400&&y<490){textDialog("Add information","Verified details",true,"ground");return true;}}
      return true;}
  }
}
