from pathlib import Path

p = Path('app/src/main/assets/index.html')
s = p.read_text(encoding='utf-8')

# Idempotency: remove the previous Studio V2 injection before rebuilding it.
import re
s = re.sub(r'<style id="asia-studio-v2-css">.*?</style>', '', s, flags=re.S)
s = re.sub(r'<section id="asiaStudioV2">.*?</section>', '', s, flags=re.S)
s = re.sub(r'<script id="asia-studio-v2-runtime">.*?</script>', '', s, flags=re.S)

css = r'''<style id="asia-studio-v2-css">
#asiaStudioV2{display:none;padding:0 0 112px}
#asiaStudioV2.on{display:block}
.studioWrap{padding:0 15px}
.studioTop{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:18px 0 12px}
.studioTop h1{font-size:24px;margin:0}.studioTop p{margin:4px 0 0;color:var(--muted);font-size:12px}
.studioTabs{display:flex;gap:7px;overflow:auto;padding-bottom:10px;scrollbar-width:none}.studioTabs::-webkit-scrollbar{display:none}
.studioTabs button{flex:0 0 auto}.studioTabs .on{background:var(--red);color:#fff}
.studioPane{display:none}.studioPane.on{display:block}
.studioStats{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-bottom:12px}
.studioStat{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:13px}.studioStat b{font-size:24px}.studioStat span{display:block;color:var(--muted);font-size:11px;margin-top:3px}
.studioCard{background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:14px;margin-bottom:10px}
.studioCard h3{margin:0 0 10px;font-size:18px}.studioGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}
.studioActions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.studioActions button{min-height:42px;border-radius:12px;padding:0 13px;background:#282a31}.studioActions .primary{background:var(--red)}.studioActions .danger{background:#5f1723}
.studioSearch{display:flex;gap:8px;margin-bottom:10px}.studioSearch input{margin:0}.studioSearch select{width:150px;margin:0}
.studioSeries{display:grid;grid-template-columns:64px 1fr;gap:11px}.studioSeries img{width:64px;height:82px;object-fit:cover;border-radius:11px;background:#1b1c22}.studioMeta{min-width:0}.studioMeta strong{font-size:16px}.studioMeta small{display:block;color:var(--muted);margin-top:3px;line-height:1.35}.studioBadge{display:inline-block;margin-top:6px;padding:4px 7px;border-radius:7px;background:#282a31;color:#bbb;font-size:10px;font-weight:900}.studioBadge.live{background:#173c29;color:#62e69b}.studioBadge.draft{background:#3a2c17;color:#f3c77d}.studioBadge.archived{background:#3a2025;color:#ef9ba7}
.studioEpisode{display:flex;gap:9px;align-items:center;border-top:1px solid var(--line);padding:10px 0}.studioEpisode:first-child{border-top:0}.studioEpisode>div:first-child{flex:1;min-width:0}.studioEpisode b{font-size:13px}.studioEpisode small{display:block;color:var(--muted);margin-top:3px}
.studioProgress{height:7px;background:#282a31;border-radius:99px;overflow:hidden;margin-top:9px}.studioProgress i{display:block;height:100%;width:0;background:var(--red)}
.studioHint{color:var(--muted);font-size:12px;line-height:1.45}.studioMsg{margin-top:8px;color:#bfc1c8;font-size:12px}.studioDanger{color:#ff8e9b}.studioEmpty{padding:20px;text-align:center;border:1px dashed #3a3c45;border-radius:14px;color:var(--muted)}
@media(max-width:520px){.studioGrid{grid-template-columns:1fr}.studioSearch{display:block}.studioSearch select{width:100%;margin-top:7px}}
</style>'''

markup = r'''<section id="asiaStudioV2">
  <div class="studioWrap">
    <div class="studioTop">
      <div><h1>Creator Studio</h1><p>Manage Asia Drama content, publishing and catalogue.</p></div>
      <button class="icon" type="button" onclick="studioRefresh()" aria-label="Refresh Studio">↻</button>
    </div>
    <div class="studioTabs">
      <button class="tab on" type="button" onclick="studioPane('overview',this)">Overview</button>
      <button class="tab" type="button" onclick="studioPane('library',this)">Library</button>
      <button class="tab" type="button" onclick="studioPane('series',this)">Series</button>
      <button class="tab" type="button" onclick="studioPane('episodes',this)">Episodes</button>
      <button class="tab" type="button" onclick="studioPane('upload',this)">Upload</button>
      <button class="tab" type="button" onclick="studioPane('orders',this)">Orders</button>
      <button class="tab" type="button" onclick="studioPane('audit',this)">Audit</button>
    </div>
    <div id="studioOverview" class="studioPane on"><div id="studioStats" class="studioStats"></div><div class="studioCard"><h3>Publishing checklist</h3><div class="studioHint">Create the series first, add seasons and episodes, upload artwork/video, then publish. Draft and archived content stay out of the public catalogue.</div><div id="studioOverviewMsg" class="studioMsg"></div></div><div class="studioCard"><h3>Recent content</h3><div id="studioRecent" class="studioEmpty">Loading…</div></div></div>
    <div id="studioLibrary" class="studioPane"><div class="studioSearch"><input id="studioSearch" class="field" placeholder="Search title, genre or language" oninput="studioRenderLibrary()"><select id="studioStatusFilter" class="field" onchange="studioRenderLibrary()"><option value="all">All status</option><option value="published">Published</option><option value="draft">Draft</option><option value="archived">Archived</option></select></div><div id="studioLibraryList"></div></div>
    <div id="studioSeries" class="studioPane"><div class="studioCard"><h3 id="studioSeriesHeading">Create series</h3><input id="studioSeriesId" type="hidden"><input id="studioSeriesTitle" class="field" placeholder="Series title"><textarea id="studioSeriesDesc" class="field area" placeholder="Description"></textarea><div class="studioGrid"><input id="studioSeriesGenre" class="field" placeholder="Genre"><input id="studioSeriesLanguage" class="field" placeholder="Language"></div><input id="studioSeriesAge" class="field" placeholder="Age rating (e.g. 13+)"><label class="small">Poster image</label><input id="studioSeriesPoster" class="field" type="file" accept="image/jpeg,image/png,image/webp,image/avif"><label class="small">Banner image</label><input id="studioSeriesBanner" class="field" type="file" accept="image/jpeg,image/png,image/webp,image/avif"><select id="studioSeriesStatus" class="field"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><div class="studioActions"><button class="primary" type="button" onclick="studioSaveSeries()">Save series</button><button type="button" onclick="studioResetSeries()">Clear</button></div><div id="studioSeriesMsg" class="studioMsg"></div></div></div>
    <div id="studioEpisodes" class="studioPane"><div class="studioCard"><h3>Episode manager</h3><select id="studioEpisodeSeries" class="field" onchange="studioLoadEpisodes()"></select><div id="studioEpisodeList"></div></div><div id="studioEpisodeEditor" class="studioCard hidden"><h3>Edit episode</h3><input id="studioEpisodeId" type="hidden"><input id="studioEditEpisodeTitle" class="field" placeholder="Episode title"><textarea id="studioEditEpisodeDesc" class="field area" placeholder="Description"></textarea><div class="studioGrid"><select id="studioEditAccess" class="field"><option value="free">Free</option><option value="pay_per_episode">Pay per episode</option><option value="subscription_only">Subscription only</option><option value="coming_soon">Coming soon</option><option value="age_restricted">Age restricted</option><option value="region_restricted">Region restricted</option></select><input id="studioEditPrice" class="field" type="number" min="0" step="1" placeholder="Price INR"></div><select id="studioEditStatus" class="field"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><div class="studioActions"><button class="primary" type="button" onclick="studioSaveEpisode()">Save episode</button><button type="button" onclick="studioCloseEpisodeEditor()">Cancel</button></div><div id="studioEpisodeMsg" class="studioMsg"></div></div></div>
    <div id="studioUpload" class="studioPane"><div class="studioCard"><h3>Upload new episode</h3><p class="studioHint">Large videos use resumable upload. Keep the app open until the upload finishes.</p><select id="studioUploadSeries" class="field"></select><div class="studioGrid"><input id="studioUploadSeason" class="field" type="number" min="1" value="1" placeholder="Season"><input id="studioUploadEpisode" class="field" type="number" min="1" value="1" placeholder="Episode"></div><input id="studioUploadSeasonTitle" class="field" placeholder="Season title (optional)"><input id="studioUploadTitle" class="field" placeholder="Episode title"><textarea id="studioUploadDesc" class="field area" placeholder="Episode description"></textarea><label class="small">Thumbnail</label><input id="studioUploadThumb" class="field" type="file" accept="image/jpeg,image/png,image/webp,image/avif"><label class="small">Video</label><input id="studioUploadVideo" class="field" type="file" accept="video/mp4,video/webm,video/quicktime"><div class="studioGrid"><select id="studioUploadAccess" class="field"><option value="free">Free</option><option value="pay_per_episode">Pay per episode</option><option value="subscription_only">Subscription only</option><option value="coming_soon">Coming soon</option></select><input id="studioUploadPrice" class="field" type="number" min="0" step="1" value="0" placeholder="Price INR"></div><input id="studioUploadPlayProduct" class="field" placeholder="Google Play product ID (paid Android content)"><select id="studioUploadStatus" class="field"><option value="draft">Save as draft</option><option value="published">Upload & publish</option></select><div class="studioActions"><button class="primary" type="button" onclick="studioUploadEpisode()">Upload episode</button></div><div id="studioUploadProgress" class="studioMsg"></div><div class="studioProgress"><i id="studioUploadBar"></i></div></div></div>
    <div id="studioOrders" class="studioPane"><div class="studioCard"><h3>Orders & subscriptions</h3><div id="studioOrdersList" class="studioEmpty">Loading…</div></div></div>
    <div id="studioAudit" class="studioPane"><div class="studioCard"><h3>Admin audit log</h3><div id="studioAuditList" class="studioEmpty">Loading…</div></div></div>
  </div>
</section>'''

s = s.replace('</body>', css + markup + '</body>', 1)

js = r'''<script id="asia-studio-v2-runtime">
(function(){
  const q=id=>document.getElementById(id); const txt=(id,v)=>{const e=q(id);if(e)e.textContent=v||''};
  const esc=v=>typeof safe==='function'?safe(v):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=p=>`₹${(Number(p||0)/100).toFixed(0)}`; let studioSeries=[]; let studioEpisodes=[]; let studioCurrentSeries='';
  async function admin(){if(!window.supabase||!window.user)return false;try{const r=await supabase.from('admin_roles').select('role').eq('user_id',user.id).limit(1).maybeSingle();return !!r.data}catch(e){return false}}
  async function uploadImage(file,bucket){if(!file)return '';const path='admin/'+user.id+'/'+Date.now()+'-'+String(file.name).replace(/[^a-zA-Z0-9._-]/g,'-');const r=await supabase.storage.from(bucket).upload(path,file,{contentType:file.type||'image/jpeg',cacheControl:'31536000',upsert:false});if(r.error)throw r.error;return supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl}
  async function uploadVideo(file){if(!file)throw Error('Select a video file.');const sess=(await supabase.auth.getSession()).data.session;if(!sess)throw Error('Please sign in again.');const bucket='asia-media',host='https://wevutronudkcqbzmverf.storage.supabase.co',path='admin/'+user.id+'/'+Date.now()+'-'+String(file.name).replace(/[^a-zA-Z0-9._-]/g,'-');const set=(p,m)=>{const b=q('studioUploadBar');if(b)b.style.width=Math.max(0,Math.min(100,p))+'%';txt('studioUploadProgress',m||('Uploading video • '+Math.floor(p)+'%'));};if(file.size<=6*1024*1024){const r=await supabase.storage.from(bucket).upload(path,file,{contentType:file.type||'video/mp4',cacheControl:'31536000',upsert:false});if(r.error)throw r.error;set(100,'Video uploaded • 100%');return 'storage://'+bucket+'/'+path}if(!window.tus)throw Error('Large-video uploader is unavailable.');await new Promise((resolve,reject)=>{const u=new tus.Upload(file,{endpoint:host+'/storage/v1/upload/resumable',retryDelays:[0,3000,5000,10000,20000],headers:{authorization:'Bearer '+sess.access_token,'x-upsert':'false'},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,metadata:{bucketName:bucket,objectName:path,contentType:file.type||'video/mp4'},chunkSize:6*1024*1024,onProgress:(a,b)=>set(b?a/b*100:0),onError:reject,onSuccess:resolve});u.findPreviousUploads().then(prev=>{if(prev.length)u.resumeFromPreviousUpload(prev[0]);u.start()}).catch(reject)});set(100,'Video uploaded • 100%');return 'storage://'+bucket+'/'+path}
  window.studioPane=function(name,btn){document.querySelectorAll('#asiaStudioV2 .studioPane').forEach(x=>x.classList.remove('on'));q('studio'+name.charAt(0).toUpperCase()+name.slice(1))?.classList.add('on');document.querySelectorAll('#asiaStudioV2 .studioTabs button').forEach(x=>x.classList.remove('on'));if(btn)btn.classList.add('on');if(name==='episodes')studioLoadEpisodes();if(name==='upload')studioLoadUploadSeries();if(name==='orders')studioLoadOrders();if(name==='audit')studioLoadAudit()};
  window.studioRefresh=async function(){if(!(await admin())){txt('studioOverviewMsg','Admin access required.');return}try{const r=await supabase.from('series').select('id,title,description,poster_url,banner_url,genre,language,age_rating,status,created_at,updated_at,seasons(id,season_number,title,episodes(id,episode_number,title,description,thumbnail_url,video_url,duration_seconds,access_type,price_paise,currency,status,release_at,play_product_id,content_type,created_at,updated_at))').order('created_at',{ascending:false});if(r.error)throw r.error;studioSeries=r.data||[];studioEpisodes=studioSeries.flatMap(s=>(s.seasons||[]).flatMap(se=>(se.episodes||[]).map(e=>({...e,series_id:s.id,series_title:s.title,season_number:se.season_number}))));studioCurrentSeries=studioCurrentSeries||studioSeries[0]?.id||'';studioRenderStats();studioRenderLibrary();studioSeriesOptions();studioRenderRecent();txt('studioOverviewMsg','Synced '+studioSeries.length+' series and '+studioEpisodes.length+' episodes.')}catch(e){txt('studioOverviewMsg',e.message||'Could not load catalogue.');toast(e.message||'Catalogue unavailable')}};
  function studioRenderStats(){const pubS=studioSeries.filter(x=>x.status==='published').length,draftS=studioSeries.filter(x=>x.status==='draft').length,pubE=studioEpisodes.filter(x=>x.status==='published').length;const o=q('studioStats');if(o)o.innerHTML=[[''+studioSeries.length,'Series'],[''+studioEpisodes.length,'Episodes'],[''+pubS,'Published series'],[''+pubE,'Published episodes'],[''+draftS,'Series drafts'],[''+studioEpisodes.filter(x=>x.status==='draft').length,'Episode drafts']].map(x=>`<div class="studioStat"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}
  function studioRenderRecent(){const o=q('studioRecent');if(!o)return;const recent=[...studioEpisodes].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,5);o.innerHTML=recent.length?recent.map(e=>`<div class="studioEpisode"><div><b>${esc(e.series_title)} • S${e.season_number} E${e.episode_number}</b><small>${esc(e.title)} · ${esc(e.status)}</small></div><span class="studioBadge ${e.status==='published'?'live':e.status==='archived'?'archived':'draft'}">${esc(e.status)}</span></div>`).join(''):'<div class="studioEmpty">No episodes yet.</div>'}
  window.studioRenderLibrary=function(){const o=q('studioLibraryList');if(!o)return;const term=(q('studioSearch')?.value||'').toLowerCase().trim(),status=q('studioStatusFilter')?.value||'all';const rows=studioSeries.filter(s=>(status==='all'||s.status===status)&&`${s.title} ${s.genre||''} ${s.language||''}`.toLowerCase().includes(term));o.innerHTML=rows.length?rows.map(s=>{const eps=(s.seasons||[]).flatMap(se=>se.episodes||[]);return `<div class="studioCard"><div class="studioSeries"><img src="${esc(s.poster_url||'icon-mark.svg')}" alt=""><div class="studioMeta"><strong>${esc(s.title)}</strong><small>${esc(s.genre||'Drama')} · ${esc(s.language||'Asia')} · ${eps.length} episodes</small><small>${esc(s.description||'No description')}</small><span class="studioBadge ${s.status==='published'?'live':s.status==='archived'?'archived':'draft'}">${esc(s.status)}</span></div></div><div class="studioActions"><button class="primary" onclick="studioEditSeries('${s.id}')">Edit</button><button onclick="studioSetSeriesStatus('${s.id}','${s.status==='published'?'draft':'published'}')">${s.status==='published'?'Unpublish':'Publish'}</button><button onclick="studioOpenEpisodeFor('${s.id}')">Manage episodes</button><button class="danger" onclick="studioArchiveSeries('${s.id}')">Archive</button></div></div>`}).join(''):'<div class="studioEmpty">No matching series.</div>'};
  function studioSeriesOptions(){[q('studioEpisodeSeries'),q('studioUploadSeries')].filter(Boolean).forEach(s=>{const old=s.value;s.innerHTML=studioSeries.map(x=>`<option value="${esc(x.id)}">${esc(x.title)}</option>`).join('')||'<option value="">Create a series first</option>';if(old)s.value=old;if(!s.value&&studioCurrentSeries)s.value=studioCurrentSeries})}
  window.studioEditSeries=function(id){const s=studioSeries.find(x=>x.id===id);if(!s)return;studioPane('series',document.querySelectorAll('#asiaStudioV2 .studioTabs button')[2]);q('studioSeriesId').value=s.id;q('studioSeriesHeading').textContent='Edit series';q('studioSeriesTitle').value=s.title||'';q('studioSeriesDesc').value=s.description||'';q('studioSeriesGenre').value=s.genre||'';q('studioSeriesLanguage').value=s.language||'';q('studioSeriesAge').value=s.age_rating||'';q('studioSeriesStatus').value=s.status||'draft';txt('studioSeriesMsg','Editing '+s.title)};
  window.studioResetSeries=function(){['studioSeriesId','studioSeriesTitle','studioSeriesDesc','studioSeriesGenre','studioSeriesLanguage','studioSeriesAge'].forEach(id=>{const e=q(id);if(e)e.value=''});q('studioSeriesStatus').value='draft';q('studioSeriesHeading').textContent='Create series';txt('studioSeriesMsg','')};
  window.studioSaveSeries=async function(){try{if(!(await admin()))throw Error('Admin access required.');const id=q('studioSeriesId').value.trim();const row={title:q('studioSeriesTitle').value.trim(),description:q('studioSeriesDesc').value.trim()||null,genre:q('studioSeriesGenre').value.trim()||null,language:q('studioSeriesLanguage').value.trim()||null,age_rating:q('studioSeriesAge').value.trim()||null,status:q('studioSeriesStatus').value};if(!row.title)throw Error('Series title is required.');const poster=q('studioSeriesPoster').files[0],banner=q('studioSeriesBanner').files[0];if(poster)row.poster_url=await uploadImage(poster,'asia-posters');if(banner)row.banner_url=await uploadImage(banner,'asia-posters');let r=id?await supabase.from('series').update({...row,updated_at:new Date().toISOString()}).eq('id',id):await supabase.from('series').insert({...row,created_by:user.id});if(r.error)throw r.error;toast(id?'Series updated':'Series created');studioResetSeries();await studioRefresh();studioPane('library',document.querySelectorAll('#asiaStudioV2 .studioTabs button')[1])}catch(e){txt('studioSeriesMsg',e.message);toast(e.message)}};
  window.studioSetSeriesStatus=async function(id,status){try{if(!(await admin()))throw Error('Admin access required.');const r=await supabase.from('series').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)throw r.error;toast('Series '+status);await studioRefresh()}catch(e){toast(e.message)}};
  window.studioArchiveSeries=async function(id){if(!confirm('Archive this series? It will no longer appear in the public catalogue.'))return;await studioSetSeriesStatus(id,'archived')};
  window.studioOpenEpisodeFor=function(id){studioCurrentSeries=id;studioPane('episodes',document.querySelectorAll('#asiaStudioV2 .studioTabs button')[3]);const s=q('studioEpisodeSeries');if(s)s.value=id;studioLoadEpisodes()};
  window.studioLoadEpisodes=async function(){const sid=q('studioEpisodeSeries')?.value||studioCurrentSeries;if(!sid){q('studioEpisodeList').innerHTML='<div class="studioEmpty">Create a series first.</div>';return}studioCurrentSeries=sid;const s=studioSeries.find(x=>x.id===sid);const eps=(s?.seasons||[]).flatMap(se=>(se.episodes||[]).map(e=>({...e,season_number:se.season_number}))).sort((a,b)=>a.season_number-b.season_number||a.episode_number-b.episode_number);const o=q('studioEpisodeList');o.innerHTML=eps.length?eps.map(e=>`<div class="studioEpisode"><div><b>S${e.season_number} E${e.episode_number} · ${esc(e.title)}</b><small>${esc(e.access_type)} ${e.price_paise?`· ${money(e.price_paise)}`:''} · ${esc(e.status)}</small></div><span class="studioBadge ${e.status==='published'?'live':e.status==='archived'?'archived':'draft'}">${esc(e.status)}</span><button onclick="studioEditEpisode('${e.id}')">Edit</button></div>`).join(''):'<div class="studioEmpty">No episodes in this series.</div>'};
  window.studioEditEpisode=function(id){const e=studioEpisodes.find(x=>x.id===id);if(!e)return;q('studioEpisodeEditor').classList.remove('hidden');q('studioEpisodeId').value=e.id;q('studioEditEpisodeTitle').value=e.title||'';q('studioEditEpisodeDesc').value=e.description||'';q('studioEditAccess').value=e.access_type||'free';q('studioEditPrice').value=e.price_paise?Number(e.price_paise)/100:0;q('studioEditStatus').value=e.status||'draft';txt('studioEpisodeMsg','Editing '+e.title);window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})};
  window.studioCloseEpisodeEditor=function(){q('studioEpisodeEditor').classList.add('hidden');txt('studioEpisodeMsg','')};
  window.studioSaveEpisode=async function(){try{if(!(await admin()))throw Error('Admin access required.');const id=q('studioEpisodeId').value;if(!id)throw Error('Select an episode.');const row={title:q('studioEditEpisodeTitle').value.trim(),description:q('studioEditEpisodeDesc').value.trim()||null,access_type:q('studioEditAccess').value,price_paise:Math.max(0,Math.round(Number(q('studioEditPrice').value||0)*100)),status:q('studioEditStatus').value,release_at:q('studioEditStatus').value==='published'?new Date().toISOString():null,updated_at:new Date().toISOString()};if(!row.title)throw Error('Episode title is required.');const r=await supabase.from('episodes').update(row).eq('id',id);if(r.error)throw r.error;toast('Episode updated');studioCloseEpisodeEditor();await studioRefresh();studioLoadEpisodes()}catch(e){txt('studioEpisodeMsg',e.message);toast(e.message)}};
  window.studioLoadUploadSeries=function(){studioSeriesOptions()};
  window.studioUploadEpisode=async function(){try{if(!(await admin()))throw Error('Admin access required.');const sid=q('studioUploadSeries').value,file=q('studioUploadVideo').files[0],title=q('studioUploadTitle').value.trim();if(!sid)throw Error('Select a series.');if(!file)throw Error('Select a video.');if(!title)throw Error('Episode title is required.');const sn=Math.max(1,parseInt(q('studioUploadSeason').value||'1',10)),en=Math.max(1,parseInt(q('studioUploadEpisode').value||'1',10));let sr=await supabase.from('seasons').select('id').eq('series_id',sid).eq('season_number',sn).maybeSingle();if(sr.error)throw sr.error;if(!sr.data){sr=await supabase.from('seasons').insert({series_id:sid,season_number:sn,title:q('studioUploadSeasonTitle').value.trim()||('Season '+sn)}).select('id').single();if(sr.error)throw sr.error}const videoUrl=await uploadVideo(file);const thumb=q('studioUploadThumb').files[0],thumbUrl=thumb?await uploadImage(thumb,'asia-posters'):'';const access=q('studioUploadAccess').value;const row={season_id:sr.data.id,episode_number:en,title,description:q('studioUploadDesc').value.trim()||null,thumbnail_url:thumbUrl||null,video_url:videoUrl,access_type:access,price_paise:Math.max(0,Math.round(Number(q('studioUploadPrice').value||0)*100)),currency:'INR',status:q('studioUploadStatus').value,release_at:q('studioUploadStatus').value==='published'?new Date().toISOString():null,play_product_id:q('studioUploadPlayProduct').value.trim()||null,content_type:'episode'};const r=await supabase.from('episodes').insert(row);if(r.error)throw r.error;toast('Episode '+(row.status==='published'?'published':'saved as draft'));['studioUploadTitle','studioUploadDesc','studioUploadPlayProduct'].forEach(id=>{q(id).value=''});q('studioUploadVideo').value='';q('studioUploadThumb').value='';txt('studioUploadProgress','Upload complete.');await studioRefresh()}catch(e){txt('studioUploadProgress',e.message||'Upload failed');toast(e.message||'Upload failed')}};
  window.studioLoadOrders=async function(){const o=q('studioOrdersList');try{if(!(await admin()))throw Error('Admin access required.');const [orders,subs]=await Promise.all([supabase.from('orders').select('id,user_id,amount_paise,currency,status,provider,created_at').order('created_at',{ascending:false}).limit(30),supabase.from('user_subscriptions').select('id,user_id,plan_name,status,current_period_end,created_at').order('created_at',{ascending:false}).limit(30)]);if(orders.error)throw orders.error;if(subs.error)throw subs.error;o.innerHTML='<b>Recent orders</b>'+((orders.data||[]).map(x=>`<div class="studioEpisode"><div><b>${esc(x.status)} · ${money(x.amount_paise)}</b><small>${esc(x.provider)} · ${esc(x.user_id)} · ${new Date(x.created_at).toLocaleString()}</small></div></div>`).join('')||'<div class="studioEmpty">No orders.</div>')+'<br><b>Subscriptions</b>'+((subs.data||[]).map(x=>`<div class="studioEpisode"><div><b>${esc(x.plan_name)} · ${esc(x.status)}</b><small>${esc(x.user_id)} · ends ${x.current_period_end?new Date(x.current_period_end).toLocaleDateString():'—'}</small></div></div>`).join('')||'<div class="studioEmpty">No subscriptions.</div>')}catch(e){o.textContent=e.message}};
  window.studioLoadAudit=async function(){const o=q('studioAuditList');try{if(!(await admin()))throw Error('Admin access required.');const r=await supabase.from('audit_logs').select('action,target_type,target_id,target_user_id,details,created_at').order('created_at',{ascending:false}).limit(50);if(r.error)throw r.error;o.innerHTML=(r.data||[]).map(x=>`<div class="studioEpisode"><div><b>${esc(x.action)}</b><small>${esc(x.target_type||'')} · ${esc(x.target_id||'')} · ${new Date(x.created_at).toLocaleString()}</small></div></div>`).join('')||'<div class="studioEmpty">No audit events yet.</div>'}catch(e){o.textContent=e.message}};
  const baseGo=window.go;window.go=function(id,nav,tab){if(id==='admin'){if(typeof baseGo==='function'){try{baseGo(id,nav,tab)}catch(_){} }q('admin')?.classList.add('hidden');q('asiaAdminCMS')?.classList.remove('on');q('asiaStudioV2')?.classList.add('on');studioRefresh();return}q('asiaStudioV2')?.classList.remove('on');q('asiaAdminCMS')?.classList.remove('on');q('admin')?.classList.remove('hidden');if(typeof baseGo==='function')return baseGo(id,nav,tab)};
  setTimeout(()=>{if(window.supabase&&window.user)studioRefresh()},700);
})();
</script>'''

s = s.replace('</body>', js + '</body>', 1)
p.write_text(s, encoding='utf-8')
print('Creator Studio V2 injected')
