#!/usr/bin/env python3
from pathlib import Path
import re

p = Path('app/src/main/assets/index.html')
s = p.read_text(encoding='utf-8')

# Stable, pinned browser uploader for large media. Supabase recommends resumable/TUS uploads for files over 6 MB.
if 'tus-js-client@4.3.1' not in s:
    s = s.replace('<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>', '<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script><script src="https://cdn.jsdelivr.net/npm/tus-js-client@4.3.1/dist/tus.min.js"></script>', 1)

admin_markup = r'''<main id="admin" class="view">
<div class="head"><h2>Business dashboard</h2><button class="link" type="button" onclick="loadAdmin()">Refresh</button></div>
<div class="adminTabs"><button class="tab on" type="button" onclick="adminPane('library',this)">Library</button><button class="tab" type="button" onclick="adminPane('series',this)">New Series</button><button class="tab" type="button" onclick="adminPane('episode',this)">Add Episode</button></div>
<section id="adminLibraryPane" class="adminPane"><div class="adminBox"><b>Content library</b><p class="small">Only published items are visible to users. Drafts stay private until you publish them.</p></div><div id="adminSeries"></div></section>
<section id="adminSeriesPane" class="adminPane hidden"><div class="adminBox"><h3 style="margin-top:0">Create series</h3><input id="adminSeriesTitle" class="field" placeholder="Series title"><textarea id="adminSeriesDesc" class="field area" placeholder="Description"></textarea><div class="grid2"><input id="adminSeriesGenre" class="field" placeholder="Genre"><input id="adminSeriesLanguage" class="field" placeholder="Language"></div><input id="adminSeriesAge" class="field" placeholder="Age rating (e.g. 13+)"><label class="small">Poster image</label><input id="adminSeriesPoster" class="field" type="file" accept="image/jpeg,image/png,image/webp,image/avif"><label class="small">Banner image (optional)</label><input id="adminSeriesBanner" class="field" type="file" accept="image/jpeg,image/png,image/webp,image/avif"><label class="setting"><span>Publish immediately</span><input id="adminSeriesPublish" type="checkbox" checked></label><button class="primary" type="button" onclick="createAdminSeries()">Create series</button><div id="adminSeriesStatus" class="status hidden"></div></div></section>
<section id="adminEpisodePane" class="adminPane hidden"><div class="adminBox"><h3 style="margin-top:0">Add episode / video</h3><select id="adminEpisodeSeries" class="field"></select><div class="grid2"><input id="adminSeasonNumber" class="field" type="number" min="1" value="1" placeholder="Season"><input id="adminEpisodeNumber" class="field" type="number" min="1" value="1" placeholder="Episode"></div><input id="adminSeasonTitle" class="field" placeholder="Season title (optional)"><input id="adminEpisodeTitle" class="field" placeholder="Episode title"><textarea id="adminEpisodeDesc" class="field area" placeholder="Episode description"></textarea><label class="small">Thumbnail image (optional)</label><input id="adminEpisodeThumb" class="field" type="file" accept="image/jpeg,image/png,image/webp,image/avif"><label class="small">Video file</label><input id="adminEpisodeVideo" class="field" type="file" accept="video/mp4,video/webm,video/quicktime"><div class="grid2"><select id="adminEpisodeAccess" class="field"><option value="free">Free</option><option value="paid">Paid</option></select><input id="adminEpisodePrice" class="field" type="number" min="0" step="1" value="0" placeholder="Price INR"></div><input id="adminPlayProductId" class="field" placeholder="Google Play product ID (required for paid Android content)"><label class="setting"><span>Publish episode</span><input id="adminEpisodePublish" type="checkbox" checked></label><div id="adminUploadProgress" class="status hidden"></div><button class="primary" type="button" onclick="createAdminEpisode()">Upload & publish episode</button></div></section>
</main></div>'''

s, n = re.subn(r'<main id="admin" class="view">.*?</main></div><nav class="nav">', admin_markup + '<nav class="nav">', s, count=1, flags=re.S)
if n != 1:
    raise SystemExit('admin markup target not found')

style = r'''<style id="asia-production-cms-v1">
.adminTabs{display:flex;gap:7px;overflow:auto;padding:0 15px 10px;scrollbar-width:none}.adminTabs::-webkit-scrollbar{display:none}.adminTabs .tab{flex:0 0 auto;min-height:44px}.adminPane{display:block}.adminBox h3{font-size:18px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:8px}.adminCard{margin:0 15px 10px;background:var(--panel);border:1px solid var(--line);border-radius:17px;padding:14px}.adminCardHead{display:flex;gap:10px;align-items:center}.adminCardHead img{width:58px;height:76px;object-fit:cover;border-radius:10px;background:#1a1b20}.adminCardMeta{flex:1}.adminEpisode{display:flex;align-items:center;gap:10px;border-top:1px solid var(--line);padding:11px 0}.adminEpisode:first-child{border-top:0}.adminBadge{font-size:10px;font-weight:900;padding:5px 7px;border-radius:7px;background:#272932;color:#bbb}.adminBadge.live{background:#173c29;color:#62e69b}.adminBadge.draft{background:#3a2c17;color:#f3c77d}.adminProgress{height:7px;border-radius:99px;background:#25272e;overflow:hidden;margin-top:8px}.adminProgress i{display:block;height:100%;width:0;background:var(--red)}
@media(max-width:520px){.grid2{grid-template-columns:1fr}}
</style>'''
s = s.replace('</head>', style + '</head>', 1)

runtime = r'''<script id="asia-production-cms-runtime-v1">
(function(){
  const MEDIA_BUCKET='asia-media', POSTER_BUCKET='asia-posters', STORAGE_HOST='https://wevutronudkcqbzmverf.storage.supabase.co';
  const PLAYBACK_API=API+'/playback-url';
  function setStatus(id,msg,show=true){const e=document.getElementById(id);if(!e)return;e.textContent=msg||'';e.classList.toggle('hidden',!show)}
  function slug(v){return String(v||'file').toLowerCase().replace(/[^a-z0-9._-]+/g,'-').replace(/-+/g,'-').slice(0,90)||'file'}
  async function session(){const r=await supabase.auth.getSession();return r.data&&r.data.session?r.data.session:null}
  async function adminCheck(){if(!user)return false;const r=await supabase.from('admin_roles').select('role').eq('user_id',user.id).limit(1).maybeSingle();return !!r.data}
  async function uploadPoster(file){if(!file)return '';const path='admin/'+user.id+'/'+Date.now()+'-'+slug(file.name);const r=await supabase.storage.from(POSTER_BUCKET).upload(path,file,{contentType:file.type||'image/jpeg',cacheControl:'31536000',upsert:false});if(r.error)throw r.error;return supabase.storage.from(POSTER_BUCKET).getPublicUrl(path).data.publicUrl}
  async function uploadVideo(file){if(!file)throw new Error('Select a video file first');const s=await session();if(!s)throw new Error('Please sign in again');const path='admin/'+user.id+'/'+Date.now()+'-'+slug(file.name);const progress=document.getElementById('adminUploadProgress');setStatus('adminUploadProgress','Preparing video upload…');
    if(file.size<=6*1024*1024){const r=await supabase.storage.from(MEDIA_BUCKET).upload(path,file,{contentType:file.type||'video/mp4',cacheControl:'31536000',upsert:false});if(r.error)throw r.error;setStatus('adminUploadProgress','Video uploaded • 100%');return 'storage://'+MEDIA_BUCKET+'/'+path}
    if(!window.tus||!window.tus.Upload)throw new Error('Large-video uploader is unavailable. Check your network and retry.');
    await new Promise((resolve,reject)=>{const upload=new tus.Upload(file,{endpoint:STORAGE_HOST+'/storage/v1/upload/resumable',retryDelays:[0,3000,5000,10000,20000],headers:{authorization:'Bearer '+s.access_token,'x-upsert':'false'},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,metadata:{bucketName:MEDIA_BUCKET,objectName:path,contentType:file.type||'video/mp4'},chunkSize:6*1024*1024,onError:reject,onProgress:function(a,b){const pct=b?Math.floor(a/b*100):0;setStatus('adminUploadProgress','Uploading video • '+pct+'%');},onSuccess:function(){resolve()}});upload.findPreviousUploads().then(function(prev){if(prev.length)upload.resumeFromPreviousUpload(prev[0]);upload.start()}).catch(reject)});
    setStatus('adminUploadProgress','Video uploaded • 100%');return 'storage://'+MEDIA_BUCKET+'/'+path
  }
  window.adminPane=function(name,btn){document.querySelectorAll('.adminPane').forEach(e=>e.classList.add('hidden'));const target=document.getElementById('admin'+name.charAt(0).toUpperCase()+name.slice(1)+'Pane');if(target)target.classList.remove('hidden');document.querySelectorAll('.adminTabs .tab').forEach(e=>e.classList.remove('on'));if(btn)btn.classList.add('on');if(name==='episode')populateEpisodeSeries()}
  async function populateEpisodeSeries(){const sel=document.getElementById('adminEpisodeSeries');if(!sel)return;const ok=await adminCheck();if(!ok){sel.innerHTML='<option>Admin access required</option>';return}const {data,error}=await supabase.from('series').select('id,title').order('created_at',{ascending:false});if(error){sel.innerHTML='<option>Unable to load series</option>';return}sel.innerHTML=(data||[]).map(x=>'<option value="'+safe(x.id)+'">'+safe(x.title)+'</option>').join('')||'<option value="">Create a series first</option>'}
  window.createAdminSeries=async function(){try{if(!(await adminCheck()))return toast('Admin access required');const title=document.getElementById('adminSeriesTitle').value.trim();if(!title)return toast('Enter a series title');const poster=document.getElementById('adminSeriesPoster').files[0];setStatus('adminSeriesStatus','Uploading artwork…');const posterUrl=await uploadPoster(poster);let bannerUrl='';const banner=document.getElementById('adminSeriesBanner').files[0];if(banner)bannerUrl=await uploadPoster(banner);const row={title,description:document.getElementById('adminSeriesDesc').value.trim(),poster_url:posterUrl||null,banner_url:bannerUrl||null,genre:document.getElementById('adminSeriesGenre').value.trim()||null,language:document.getElementById('adminSeriesLanguage').value.trim()||null,age_rating:document.getElementById('adminSeriesAge').value.trim()||null,status:document.getElementById('adminSeriesPublish').checked?'published':'draft',created_by:user.id};const r=await supabase.from('series').insert(row).select('id').single();if(r.error)throw r.error;setStatus('adminSeriesStatus','Series created successfully.');toast('Series created');document.getElementById('adminSeriesTitle').value='';await loadCatalog();await loadAdmin();adminPane('episode',document.querySelectorAll('.adminTabs .tab')[2])}catch(e){setStatus('adminSeriesStatus',e.message||'Could not create series');toast(e.message||'Create failed')}}
  window.createAdminEpisode=async function(){try{if(!(await adminCheck()))return toast('Admin access required');const seriesId=document.getElementById('adminEpisodeSeries').value;if(!seriesId)return toast('Create a series first');const video=document.getElementById('adminEpisodeVideo').files[0];if(!video)return toast('Select a video file');const title=document.getElementById('adminEpisodeTitle').value.trim();if(!title)return toast('Enter episode title');const seasonNo=Math.max(1,parseInt(document.getElementById('adminSeasonNumber').value||'1',10));const episodeNo=Math.max(1,parseInt(document.getElementById('adminEpisodeNumber').value||'1',10));setStatus('adminUploadProgress','Creating season…');let season=await supabase.from('seasons').select('id').eq('series_id',seriesId).eq('season_number',seasonNo).maybeSingle();if(season.error)throw season.error;if(!season.data){const sr=await supabase.from('seasons').insert({series_id:seriesId,season_number:seasonNo,title:document.getElementById('adminSeasonTitle').value.trim()||('Season '+seasonNo)}).select('id').single();if(sr.error)throw sr.error;season.data=sr.data}const videoUrl=await uploadVideo(video);let thumbUrl='';const thumb=document.getElementById('adminEpisodeThumb').files[0];if(thumb)thumbUrl=await uploadPoster(thumb);const access=document.getElementById('adminEpisodeAccess').value;const price=Math.max(0,Math.round(Number(document.getElementById('adminEpisodePrice').value||0)*100));if(access==='paid'&&!document.getElementById('adminPlayProductId').value.trim())throw new Error('Google Play product ID is required for paid Android content');const row={season_id:season.data.id,episode_number:episodeNo,title,description:document.getElementById('adminEpisodeDesc').value.trim()||null,thumbnail_url:thumbUrl||null,video_url:videoUrl,duration_seconds:null,access_type:access,price_paise:price,currency:'INR',status:document.getElementById('adminEpisodePublish').checked?'published':'draft',release_at:document.getElementById('adminEpisodePublish').checked?new Date().toISOString():null,play_product_id:document.getElementById('adminPlayProductId').value.trim()||null,content_type:'episode'};const er=await supabase.from('episodes').insert(row).select('id').single();if(er.error)throw er.error;setStatus('adminUploadProgress','Episode published successfully.');toast('Episode published');await loadCatalog();await loadAdmin()}catch(e){setStatus('adminUploadProgress',e.message||'Upload failed');toast(e.message||'Upload failed')}}
  function renderAdminLibrary(){const host=document.getElementById('adminSeries');if(!host)return;if(!catalog.length){host.innerHTML='<div class="empty">No series yet. Create your first series.</div>';return}host.innerHTML=catalog.map(x=>{const eps=[];(x.seasons||[]).forEach(s=>(s.episodes||[]).forEach(e=>eps.push({...e,season:s.season_number})));return '<article class="adminCard"><div class="adminCardHead"><img src="'+safe(x.poster_url||'icon-mark.svg')+'" alt=""><div class="adminCardMeta"><b>'+safe(x.title)+'</b><div class="small">'+safe(x.genre||'Drama')+' • '+safe(x.language||'Asia')+'</div><div class="small">'+safe(x.status||'draft')+'</div></div></div><div style="margin-top:10px">'+(eps.length?eps.map(e=>'<div class="adminEpisode"><div style="flex:1"><b>S'+safe(e.season)+' E'+safe(e.episode_number)+' • '+safe(e.title)+'</b><div class="small">'+safe(e.access_type||'free')+'</div></div><span class="adminBadge '+(e.status==='published'?'live':'draft')+'">'+safe(e.status||'draft')+'</span></div>').join(''):'<div class="empty">No episodes yet.</div>')+'</div></article>'}).join('')}
  window.loadAdmin=async function(){if(!(await adminCheck())){document.getElementById('adminButton')?.classList.add('hidden');return openSheet('auth')}renderAdminLibrary();populateEpisodeSeries()}
  const oldGo=window.go;window.go=function(id,nav,tab){oldGo(id,nav);if(tab&&tab.classList){document.querySelectorAll('.tabs .tab').forEach(e=>e.classList.remove('on'));tab.classList.add('on')}if(id==='admin')loadAdmin()}
  window.playEpisode=async function(id,title,url,paid){if(paid){if(!user)return openSheet('auth');return startRazorpay(id,title)}const s=await session();if(!s)return openSheet('auth');try{mediaMessage('Checking playback access…');const r=await fetch(PLAYBACK_API+'?episode_id='+encodeURIComponent(id),{headers:{Authorization:'Bearer '+s.access_token}});const j=await r.json();if(!r.ok)throw new Error(j.error||'Playback unavailable');currentEpisodeId=id;lastProgressSent=-1;closeSheet();document.getElementById('playerTitle').textContent=title||j.title||'Asia Drama';const v=document.getElementById('video');v.pause();v.removeAttribute('src');v.load();v.src=j.url;v.preload='metadata';v.controls=true;v.playsInline=true;document.getElementById('player').classList.add('on');mediaMessage('Loading video…');const done=()=>mediaMessage('');v.onloadedmetadata=done;v.onplaying=done;v.onwaiting=()=>mediaMessage('Buffering…');v.onerror=()=>mediaMessage('Video could not be played. Check the media format and network.');v.play().catch(()=>{});}catch(e){mediaMessage('');toast(e.message||'Playback unavailable')}}
  const oldBoot=window.boot;window.boot=async function(){await oldBoot();const ok=await adminCheck();document.getElementById('adminButton')?.classList.toggle('hidden',!ok);if(ok&&document.getElementById('adminSeries'))renderAdminLibrary()}
  // The original script calls boot() before this override exists, so run the corrected boot once now.
  setTimeout(()=>window.boot(),0);
})();
</script>'''
s = s.replace('</body>', runtime + '</body>', 1)

# The catalogue intentionally omits raw video_url; route playback through the secure signed-URL function.
s = s.replace("onclick=\"playEpisode('${e.id}','${safe(e.title)}','${safe(e.video_url||'')}','${paid}')\"", "onclick=\"playEpisode('${e.id}','${safe(e.title)}','',${paid})\"", 1)

p.write_text(s, encoding='utf-8')
print('production CMS and secure playback patch applied')
